import { DocumentBlock, DocumentContentJson } from '@/lib/types';

export interface AgencyTemplate {
  key: string;
  category: 'product_brief' | 'meeting_notes' | 'spec' | 'sop' | 'proposal';
  title: string;
  subtitle: string;
  description: string;
  badge: string;
  iconName: 'FileText' | 'Calendar' | 'FileCode2' | 'CheckSquare' | 'Sparkles';
  defaultBlocks: DocumentBlock[];
}

export const AGENCY_TEMPLATES: AgencyTemplate[] = [
  {
    key: 'product_brief',
    category: 'product_brief',
    title: 'Dossier Produit & Vision',
    subtitle: 'Cadrage stratégique, ICP, fonctionnalités et modèle économique',
    description: 'Structure complète pour formaliser une application ou solution de l\'agence (ex: Minerva Flow).',
    badge: 'Produit & Stratégie',
    iconName: 'Sparkles',
    defaultBlocks: [
      { id: 'pb-1', type: 'heading_1', content: 'Dossier Produit — Vision & Offre Pilote' },
      {
        id: 'pb-2',
        type: 'callout',
        content: '**Concept en 1 phrase** : Décrire ici la promesse centrale du produit et sa proposition de valeur unique pour le client final.',
        calloutType: 'info',
      },
      { id: 'pb-3', type: 'heading_2', content: '1. Problème Résolu & Enjeux Marché' },
      {
        id: 'pb-4',
        type: 'paragraph',
        content: 'Quelles sont les frictions opérationnelles, pertes de temps ou surcoûts actuels rencontrés par les prospects cibles ?',
      },
      { id: 'pb-5', type: 'heading_2', content: '2. ICP (Profil Client Idéal)' },
      {
        id: 'pb-6',
        type: 'bullet_list',
        content: 'Type d\'établissement ou entreprise cible (ex: Restaurants service aux tables, Cafés de quartier)',
      },
      {
        id: 'pb-7',
        type: 'bullet_list',
        content: 'Fourchette de chiffre d\'affaires ou taille d\'équipe (ex: 5 à 25 employés)',
      },
      {
        id: 'pb-8',
        type: 'bullet_list',
        content: 'Localisation géographique prioritaire (ex: Grand Montréal, Québec)',
      },
      { id: 'pb-9', type: 'heading_2', content: '3. Fonctionnalités Clés & Livrables' },
      { id: 'pb-10', type: 'todo_list', content: 'Tableau de bord de pilotage des revenus quotidiens', checked: false },
      { id: 'pb-11', type: 'todo_list', content: 'Suivi des marges commerciales & coûts opérationnels', checked: false },
      { id: 'pb-12', type: 'todo_list', content: 'Automatisation des flux SMS et relances clients', checked: false },
      { id: 'pb-13', type: 'todo_list', content: 'Passerelle de commande QR code et paiement sans friction', checked: false },
      { id: 'pb-14', type: 'heading_2', content: '4. Offre Pilote & Conditions 90 Jours' },
      {
        id: 'pb-15',
        type: 'callout',
        content: '**Protocole Pilote** : 3 à 5 partenaires sélectionnés. Gratuité totale sur 90 jours en échange d\'une session de feedback structurée par semaine.',
        calloutType: 'tip',
      },
      {
        id: 'pb-16',
        type: 'table',
        content: 'Conditions de l\'offre',
        tableData: [
          ['Paramètre', 'Offre Pilote (90j)', 'Tarification Standard'],
          ['Investissement', '0 $ CAD', '250 $ - 500 $/mois'],
          ['Accompagnement', 'Support direct Fondateur / Tech Lead', 'Support standard par ticket'],
          ['Engagement', '1h de revue / semaine', 'Sans engagement'],
        ],
      },
    ],
  },
  {
    key: 'meeting_notes',
    category: 'meeting_notes',
    title: 'Compte-Rendu de Réunion',
    subtitle: 'Ordre du jour, décisions actées, responsabilités et prochaines étapes',
    description: 'Format standardisé pour les kickoffs clients, synchronisations hebdomadaires et comités de projet.',
    badge: 'Opérations & Sync',
    iconName: 'Calendar',
    defaultBlocks: [
      { id: 'mn-1', type: 'heading_1', content: 'Compte-Rendu — Synchronisation Projet' },
      {
        id: 'mn-2',
        type: 'callout',
        content: '**Détails de la séance** : Date : ' + new Date().toLocaleDateString('fr-CA') + ' | Durée : 45 min | Animateur : Équipe Minerva | Participants : Client & Équipe Minerva',
        calloutType: 'note',
      },
      { id: 'mn-3', type: 'heading_2', content: '1. Ordre du Jour & Objectifs' },
      { id: 'mn-4', type: 'bullet_list', content: 'Revue des livrables de la semaine précédente' },
      { id: 'mn-5', type: 'bullet_list', content: 'Validation de l\'arborescence et de l\'expérience mobile' },
      { id: 'mn-6', type: 'bullet_list', content: 'Point de blocage sur l\'intégration API de paiement' },
      { id: 'mn-7', type: 'heading_2', content: '2. Décisions Actées' },
      {
        id: 'mn-8',
        type: 'callout',
        content: '**Décision clé** : Prioriser le déploiement mobile-first avant l\'intégration des fonctionnalités secondaires.',
        calloutType: 'tip',
      },
      { id: 'mn-9', type: 'paragraph', content: 'Les maquettes Framer sont validées avec la palette de couleurs Crème Chaud & Émeraude.' },
      { id: 'mn-10', type: 'heading_2', content: '3. Plan d\'Action & Prochaines Étapes' },
      {
        id: 'mn-11',
        type: 'table',
        content: 'Grille d\'action',
        tableData: [
          ['Tâche', 'Responsable', 'Échéance', 'Statut'],
          ['Ajuster les formulaires de capture de leads', 'Tech & IA', 'J+3', 'À faire'],
          ['Fournir les photos haute résolution du menu', 'Client', 'J+5', 'En attente'],
          ['Mettre en ligne la version de staging', 'Delivery', 'J+7', 'Prévu'],
        ],
      },
      { id: 'mn-12', type: 'heading_2', content: '4. Notes Libres & Remarques' },
      { id: 'mn-13', type: 'paragraph', content: 'Prochaine réunion fixée au vendredi suivant à 10h00 via visioconférence.' },
    ],
  },
  {
    key: 'spec',
    category: 'spec',
    title: 'Cahier des Charges & Delivery',
    subtitle: 'Périmètre fonctionnel, architecture technique, APIs et recette QA',
    description: 'Document de cadrage technique complet pour encadrer le développement sans dérive de scope.',
    badge: 'Technique & QA',
    iconName: 'FileCode2',
    defaultBlocks: [
      { id: 'sp-1', type: 'heading_1', content: 'Spécifications Techniques & Cahier des Charges' },
      {
        id: 'sp-2',
        type: 'callout',
        content: '**Cadre de Réalisation** : Document contractuel de cadrage technique. Toute modification majeure du périmètre fera l\'objet d\'un avenant.',
        calloutType: 'warning',
      },
      { id: 'sp-3', type: 'heading_2', content: '1. Architecture & Stack Technique' },
      { id: 'sp-4', type: 'bullet_list', content: 'Frontend : Next.js 16 (App Router), React 19, Tailwind CSS' },
      { id: 'sp-5', type: 'bullet_list', content: 'Backend & Base de données : Supabase (Postgres, Auth, Realtime, RLS)' },
      { id: 'sp-6', type: 'bullet_list', content: 'Hébergement & CI/CD : Vercel + GitHub Actions' },
      { id: 'sp-7', type: 'heading_2', content: '2. Modules & Périmètre Fonctionnel' },
      { id: 'sp-8', type: 'todo_list', content: 'Authentification sécurisée avec rôles différenciés', checked: false },
      { id: 'sp-9', type: 'todo_list', content: 'Tableau de bord haute densité avec widgets analytiques', checked: false },
      { id: 'sp-10', type: 'todo_list', content: 'Synchronisation temps réel des données d\'exploitation', checked: false },
      { id: 'sp-11', type: 'todo_list', content: 'Export des rapports au format Markdown & PDF soigné', checked: false },
      { id: 'sp-12', type: 'heading_2', content: '3. Protocole de Recette & QA' },
      { id: 'sp-13', type: 'paragraph', content: 'Critères d\'acceptation avant mise en production :' },
      { id: 'sp-14', type: 'bullet_list', content: 'Score Lighthouse Performance > 90 sur mobile' },
      { id: 'sp-15', type: 'bullet_list', content: 'Temps de réponse serveur (TTFB) < 200 ms' },
      { id: 'sp-16', type: 'bullet_list', content: 'Validation zéro erreur TypeScript et conformité RLS' },
    ],
  },
  {
    key: 'sop',
    category: 'sop',
    title: 'SOP & Process Interne',
    subtitle: 'Standard Operating Procedure : protocole étape par étape et contrôles qualité',
    description: 'Document de standardisation opérationnelle pour l\'académie interne de l\'agence.',
    badge: 'Académie & Process',
    iconName: 'CheckSquare',
    defaultBlocks: [
      { id: 'sop-1', type: 'heading_1', content: 'SOP — Protocole Opérationnel Interne' },
      {
        id: 'sop-2',
        type: 'callout',
        content: '**Principe Minerva** : « Donner d’abord, demander ensuite ». Chaque étape doit minimiser la friction pour le client et maximiser la valeur délivrée dès la première interaction.',
        calloutType: 'tip',
      },
      { id: 'sop-3', type: 'heading_2', content: '1. Objectif & Champ d\'Application' },
      {
        id: 'sop-4',
        type: 'paragraph',
        content: 'Définir la procédure exacte à suivre lors de l\'intégration d\'un nouveau client ou de la livraison d\'un projet.',
      },
      { id: 'sop-5', type: 'heading_2', content: '2. Prérequis & Outils Nécessaires' },
      { id: 'sop-6', type: 'bullet_list', content: 'Accès administrateur au projet Supabase et au compte Framer' },
      { id: 'sop-7', type: 'bullet_list', content: 'Informations de facturation et contrat signé' },
      { id: 'sop-8', type: 'bullet_list', content: 'Assets de marque du client (logo SVG, typographies, palette)' },
      { id: 'sop-9', type: 'heading_2', content: '3. Étapes d\'Exécution Chronologiques' },
      { id: 'sop-10', type: 'todo_list', content: 'Étape 1 : Créer la fiche client sur Minerva (/clients)', checked: false },
      { id: 'sop-11', type: 'todo_list', content: 'Étape 2 : Générer le lien d\'invitation sécurisé pour le portail client', checked: false },
      { id: 'sop-12', type: 'todo_list', content: 'Étape 3 : Configurer les canaux de communication dédiés', checked: false },
      { id: 'sop-13', type: 'todo_list', content: 'Étape 4 : Programmer la session de cadrage 45 min', checked: false },
      { id: 'sop-14', type: 'heading_2', content: '4. Checklist de Contrôle Qualité' },
      {
        id: 'sop-15',
        type: 'callout',
        content: '**Contrôle obligatoire** : Vérifier que les variables d\'environnement en production sont strictement isolées des clés de test.',
        calloutType: 'warning',
      },
    ],
  },
  {
    key: 'proposal',
    category: 'proposal',
    title: 'Proposition Commerciale & Devis',
    subtitle: 'Diagnostic du prospect, solution recommandée, calendrier et chiffrage (CAD)',
    description: 'Format professionnel de proposition stratégique pour closing de prospects qualifiés.',
    badge: 'Vente & Devis',
    iconName: 'FileText',
    defaultBlocks: [
      { id: 'pr-1', type: 'heading_1', content: 'Proposition Commerciale Stratégique' },
      {
        id: 'pr-2',
        type: 'callout',
        content: '**Client** : Prospect Partenaire | Préparé par : Agence Minerva | Date d\'émission : ' + new Date().toLocaleDateString('fr-CA') + ' | Validité : 14 jours',
        calloutType: 'note',
      },
      { id: 'pr-3', type: 'heading_2', content: '1. Diagnostic de Situation' },
      {
        id: 'pr-4',
        type: 'paragraph',
        content: 'Suite à notre échange diagnostic, nous avons identifié plusieurs gisements de croissance inexploités et des points de friction sur le parcours client actuel.',
      },
      { id: 'pr-5', type: 'heading_2', content: '2. Solution Recommandée (Système Minerva)' },
      { id: 'pr-6', type: 'bullet_list', content: 'Déploiement d\'une interface mobile ultrarapide axée conversion' },
      { id: 'pr-7', type: 'bullet_list', content: 'Mise en place d\'un suivi automatisé des leads sous 5 minutes par SMS/WhatsApp' },
      { id: 'pr-8', type: 'bullet_list', content: 'Cockpit analytique pour mesurer le ROI exact et le chiffre d\'affaires généré' },
      { id: 'pr-9', type: 'heading_2', content: '3. Grille d\'Investissement & Modalités' },
      {
        id: 'pr-10',
        type: 'table',
        content: 'Investissement',
        tableData: [
          ['Prestation / Module', 'Délai', 'Investissement (CAD)'],
          ['Phase 1 : Architecture, Design & Intégration', '2 semaines', '3 500 $'],
          ['Phase 2 : Automatisations CRM & Connexions APIs', '1 semaine', '1 500 $'],
          ['Co-pilotage & Maintenance Opérationnelle', 'Mensuel', '450 $/mois'],
          ['TOTAL DÉMARRAGE', '3 semaines', '5 000 $ CAD'],
        ],
      },
      { id: 'pr-11', type: 'heading_2', content: '4. Prochaines Étapes pour Démarrer' },
      { id: 'pr-12', type: 'todo_list', content: 'Validation de la proposition et signature du bon de commande', checked: false },
      { id: 'pr-13', type: 'todo_list', content: 'Versement de l\'acompte de 50 % de démarrage', checked: false },
      { id: 'pr-14', type: 'todo_list', content: 'Kickoff meeting et lancement du sprint de design', checked: false },
    ],
  },
];
