import { Client, ClientRoiMetrics, Project, ProjectRoadmapStep, LaunchCheckItem, ContentPost, TeamMemberPerformance, AcademySOP } from './types';

export const INITIAL_CLIENTS: Client[] = [
  {
    id: 'client-apex-roofing',
    name: 'Apex Roofing',
    logo_url: 'https://images.unsplash.com/photo-1541888946425-d0fbb186a5b3?w=150&auto=format&fit=crop&q=80',
    industry: 'Toiture & Bâtiment',
    status: 'Active',
    mrr: 3800,
    health_status: 'Ready',
    contact_name: 'David Miller',
    contact_email: 'david@apexroofing.ca',
    created_at: '2026-01-15T00:00:00Z',
  },
  {
    id: 'client-cafe-st-henri',
    name: 'Café Saint-Henri',
    logo_url: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=150&auto=format&fit=crop&q=80',
    industry: 'Restauration & Cafés',
    status: 'Active',
    mrr: 2400,
    health_status: 'On Track',
    contact_name: 'Sophie Tremblay',
    contact_email: 'sophie@sthenricafe.com',
    created_at: '2026-02-01T00:00:00Z',
  },
  {
    id: 'client-clinique-sante',
    name: 'Clinique Santé Moderne',
    logo_url: 'https://images.unsplash.com/photo-1629909613654-28e377c37b09?w=150&auto=format&fit=crop&q=80',
    industry: 'Santé & Médical',
    status: 'Onboarding',
    mrr: 4500,
    health_status: 'Ready',
    contact_name: 'Dr. Marc-André Côté',
    contact_email: 'direction@cliniquesante.qc.ca',
    created_at: '2026-03-10T00:00:00Z',
  },
  {
    id: 'client-boreale-avocats',
    name: 'Boréale Avocats',
    logo_url: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=150&auto=format&fit=crop&q=80',
    industry: 'Droit & Juridique',
    status: 'Active',
    mrr: 5200,
    health_status: 'On Track',
    contact_name: 'Me Élodie Roy',
    contact_email: 'elodie@boreale-avocats.ca',
    created_at: '2026-04-05T00:00:00Z',
  },
];

export const MOCK_ROI_METRICS: Record<string, ClientRoiMetrics> = {
  'client-apex-roofing': {
    id: 'roi-apex',
    client_id: 'client-apex-roofing',
    leads_sent_30d: 47,
    leads_change_pct: 34,
    sales_completed: 18,
    conversion_rate_pct: 38,
    cost_per_lead: 23,
    pipeline_value: 48200,
    roi_multiplier: 8.7,
    total_invested: 5540,
    total_generated: 48200,
    top_keywords_rank_top3: 6,
    total_keywords_tracked: 14,
    gmb_reviews_count: 34,
    gmb_rating: 4.9,
    gmb_calls_count: 29,
    google_ads_spent: 1240,
    google_ads_leads: 32,
    google_ads_roas: 6.2,
    weekly_leads_trend: [8, 11, 9, 14, 12, 16, 19],
  },
  'client-cafe-st-henri': {
    id: 'roi-st-henri',
    client_id: 'client-cafe-st-henri',
    leads_sent_30d: 31,
    leads_change_pct: 18,
    sales_completed: 12,
    conversion_rate_pct: 35,
    cost_per_lead: 18,
    pipeline_value: 19400,
    roi_multiplier: 6.4,
    total_invested: 3030,
    total_generated: 19400,
    top_keywords_rank_top3: 4,
    total_keywords_tracked: 10,
    gmb_reviews_count: 88,
    gmb_rating: 4.8,
    gmb_calls_count: 42,
    google_ads_spent: 850,
    google_ads_leads: 21,
    google_ads_roas: 5.1,
    weekly_leads_trend: [4, 6, 7, 8, 9, 11, 13],
  },
};

export const INITIAL_PROJECTS: Project[] = [
  {
    id: 'proj-apex-launch',
    client_id: 'client-apex-roofing',
    client_name: 'Apex Roofing',
    name: 'Refonte Site Framer & Automation Leads',
    current_stage: 'Launch Check',
    health: 'Ready',
    progress_pct: 90,
    due_date: '2026-08-15',
    assignees: ['Alex Tremblay', 'Sarah Bouchard'],
  },
  {
    id: 'proj-st-henri-framer',
    client_id: 'client-cafe-st-henri',
    client_name: 'Café Saint-Henri',
    name: 'Site Mobile-First & Click-to-WhatsApp',
    current_stage: 'Design Framer',
    health: 'On Track',
    progress_pct: 65,
    due_date: '2026-08-22',
    assignees: ['Alex Tremblay'],
  },
  {
    id: 'proj-clinique-ia',
    client_id: 'client-clinique-sante',
    client_name: 'Clinique Santé Moderne',
    name: 'Agent Prise de RDV IA & Missed-call Text-back',
    current_stage: 'Onboarding',
    health: 'On Track',
    progress_pct: 30,
    due_date: '2026-09-01',
    assignees: ['Sarah Bouchard', 'Mathieu Gagnon'],
  },
];

export const INITIAL_LAUNCH_CHECKITEMS: LaunchCheckItem[] = [
  { id: 1, title: 'Page 404 Personnalisée', description: 'Design sur-mesure avec lien retour accueil et recherche', category: 'UX/UI & Design', checked: false },
  { id: 2, title: 'CTA Clair Above The Fold', description: 'Bouton d’action principal visible sans scroll avec forte accroche', category: 'UX/UI & Design', checked: true },
  { id: 3, title: 'Maillage Interne Structuré', description: 'Liens logiques entre pages de services et études de cas', category: 'UX/UI & Design', checked: true },
  { id: 4, title: 'Thank You Page configurée', description: 'Redirection après formulaire avec tracking de conversion', category: 'Conversion & Analytics', checked: true },
  { id: 5, title: 'Fil d’Ariane (Breadcrumbs) Active', description: 'Fil d’ariane accessible pour l’utilisateur et le SEO Google', category: 'UX/UI & Design', checked: true },
  { id: 6, title: 'Section Études de Cas Présente', description: 'Témoignages et résultats chiffrés réels intégrés', category: 'SEO & Content', checked: true },
  { id: 7, title: 'Foire Aux Questions (F.A.Q)', description: 'Réponses aux 5 objections principales des prospects', category: 'SEO & Content', checked: true },
  { id: 8, title: 'Engagement de temps de réponse affiché', description: 'Ex: "Rappel garanti en moins de 15 minutes"', category: 'UX/UI & Design', checked: true },
  { id: 9, title: 'Sticky Mobile CTA Configuré', description: 'Barre d’appel fixe en bas d’écran sur mobile', category: 'UX/UI & Design', checked: true },
  { id: 10, title: 'Fichier Robots.txt & Sitemap OK', description: 'Sitemap XML généré et soumis à la Google Search Console', category: 'SEO & Content', checked: true },
  { id: 11, title: 'Titres de Pages Uniques & H1/H2', description: 'Structure hiérarchique stricte par page', category: 'SEO & Content', checked: true },
  { id: 12, title: 'Méta-descriptions optimisées', description: 'Méta-description unique entre 140 et 160 caractères', category: 'SEO & Content', checked: true },
  { id: 13, title: 'Visuels Social Share (Open Graph)', description: 'Image og:image 1200x630px configurée pour les partages SMS/Social', category: 'SEO & Content', checked: true },
  { id: 14, title: 'Google Maps & Itinéraire Intégré', description: 'Carte interactive et fiche GMB liée', category: 'UX/UI & Design', checked: true },
  { id: 15, title: 'Avis Clients Authentiques Intégrés', description: 'Synchro en direct avec la fiche Google Business Profile', category: 'SEO & Content', checked: true },
  { id: 16, title: 'Balises Alt sur toutes les images', description: 'Description textuelle pour l’accessibilité et le SEO', category: 'SEO & Content', checked: true },
  { id: 17, title: 'Conforme Loi 25 (Bannière & Consentement)', description: 'Politique de confidentialité et gestionnaire de cookies actif', category: 'Performance & Legal', checked: false },
  { id: 18, title: 'Vitesse Mobile < 2.0s', description: 'Lighthouse Performance score > 90/100 sur mobile', category: 'Performance & Legal', checked: true },
  { id: 19, title: 'Google Analytics & Pixels Ads Actifs', description: 'Google Tag Manager + Meta Pixel sans erreur', category: 'Conversion & Analytics', checked: true },
  { id: 20, title: 'Photos réelles de l’Équipe affichées', description: 'Pas de visuels génériques de banque d’images', category: 'SEO & Content', checked: true },
];

export const INITIAL_TEAM: TeamMemberPerformance[] = [
  {
    id: 'team-alex',
    profile_id: 'prof-alex',
    full_name: 'Alex Tremblay',
    role: 'Développeur Fullstack & Lead IA',
    avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    next_1on1_date: '2026-08-13T14:00:00Z',
    feedbacks_count: 12,
    okrs: [
      { id: 'okr-1', title: 'Finaliser le moteur de scraping Minerva Reach', target_pct: 100, current_pct: 90 },
      { id: 'okr-2', title: 'Intégrer la Checklist de Lancement dans Centurions', target_pct: 100, current_pct: 85 },
      { id: 'okr-3', title: 'Automatiser les webhooks Stripe & Meta Ads', target_pct: 100, current_pct: 60 },
    ],
    skills: [
      { skill: 'Intégration Framer & Tailwind CSS', level: 'Expert' },
      { skill: 'Workflows Automatisés IA & Webhooks', level: 'Avancé' },
      { skill: 'Configuration API Google Ads / Meta Ads', level: 'En apprentissage' },
      { skill: 'Supabase & Edge Functions', level: 'Avancé' },
    ],
  },
  {
    id: 'team-sarah',
    profile_id: 'prof-sarah',
    full_name: 'Sarah Bouchard',
    role: 'Head of Client Growth & Success',
    avatar_url: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    next_1on1_date: '2026-08-14T10:30:00Z',
    feedbacks_count: 8,
    okrs: [
      { id: 'okr-4', title: 'Atteindre 15 000 $ de MRR sur les comptes clés', target_pct: 100, current_pct: 80 },
      { id: 'okr-5', title: 'Réduire le délai moyen d’onboarding client à 5 jours', target_pct: 100, current_pct: 95 },
    ],
    skills: [
      { skill: 'Gestion de Relation Client (CRM)', level: 'Expert' },
      { skill: 'Stratégie Acquisition Ads', level: 'Avancé' },
      { skill: 'Analyse ROI & Analytics', level: 'Expert' },
    ],
  },
];

export const INITIAL_SOPS: AcademySOP[] = [
  {
    id: 'sop-framer-launch',
    title: 'Standard de Déploiement Framer Mobile-First',
    category: 'Design Framer',
    read_time_min: 8,
    author: 'Alex Tremblay',
    video_url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    description: 'Protocole complet pour convertir un Figma vers Framer en assurant des temps de chargement sous 1.8s et un layout responsive impeccable.',
  },
  {
    id: 'sop-loi-25',
    title: 'Conformité Loi 25 au Québec pour les sites clients',
    category: 'Loi 25 & Compliance',
    read_time_min: 12,
    author: 'Me Élodie Roy',
    description: 'Guide étape par étape pour configurer les politiques de confidentialité, l’opt-in SMS et le gestionnaire de consentement cookies.',
  },
  {
    id: 'sop-whatsapp-ai',
    title: 'Configuration Bot Agent IA WhatsApp & Make/n8n',
    category: 'Workflows IA',
    read_time_min: 15,
    author: 'Alex Tremblay',
    video_url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    description: 'Architecture des webhooks et des prompts system pour relancer automatiquement les leads manqués en moins de 60 secondes.',
  },
];
